from typing import Dict

from installer.sources import WheelSource
from installer import install as _install
from packaging.version import Version

from pipm._installer.destinations import WheelMultiDestination


def install(
    source: WheelSource,
    destination: WheelMultiDestination,
    additional_metadata: Dict[str, bytes],
) -> None:
    """Install wheel described by ``source`` into ``destination``.

    :param source: wheel to install.
    :param destination: where to write the wheel.
    :param additional_metadata: additional metadata files to generate, usually
                                generated by the installer.

    """
    destination.distribution = source.distribution
    destination.version = Version(source.version)

    try:
        _install(source, destination, additional_metadata)
    except FileExistsError:
        pass
